name: Check Boba Availability

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-boba:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create env file
      run: |
        echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" > .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}" >> .env
        echo "WAS_UNAVAILABLE=${{ secrets.WAS_UNAVAILABLE }}" >> .env
    
    - name: Run boba checker
      run: python boba_checker.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 